app:
  location: 'uksouth' # run `az account list-locations` to get name of your location
  name: 'derrentest'
  spas:
    dashboard:
      app_path: '/dash'
      project_folder_path: ~/git/derren-test-project/dashboard
      # compile_cmd: 'npm install && npm build'
    marketing:
      app_path: '/'
      project_folder_path: ~/git/derren-test-project/marketing
    admin:
      app_path: '/admin'
      project_folder_path: ~/git/derren-test-project/admin
  environments:
    - prod
    - stg
    - dev

